# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from roborts_msgs/RobotStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class RobotStatus(genpy.Message):
  _md5sum = "e4295b144c261ec35e3a477c577c8639"
  _type = "roborts_msgs/RobotStatus"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """#robot status
uint8 id
uint8 level
uint16 remain_hp
uint16 max_hp

uint16 heat_cooling_rate
uint16 heat_cooling_limit
uint16 heat_speed_limit

bool gimbal_enable
bool chassis_enable
bool shooter_enable"""
  __slots__ = ['id','level','remain_hp','max_hp','heat_cooling_rate','heat_cooling_limit','heat_speed_limit','gimbal_enable','chassis_enable','shooter_enable']
  _slot_types = ['uint8','uint8','uint16','uint16','uint16','uint16','uint16','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,level,remain_hp,max_hp,heat_cooling_rate,heat_cooling_limit,heat_speed_limit,gimbal_enable,chassis_enable,shooter_enable

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RobotStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.level is None:
        self.level = 0
      if self.remain_hp is None:
        self.remain_hp = 0
      if self.max_hp is None:
        self.max_hp = 0
      if self.heat_cooling_rate is None:
        self.heat_cooling_rate = 0
      if self.heat_cooling_limit is None:
        self.heat_cooling_limit = 0
      if self.heat_speed_limit is None:
        self.heat_speed_limit = 0
      if self.gimbal_enable is None:
        self.gimbal_enable = False
      if self.chassis_enable is None:
        self.chassis_enable = False
      if self.shooter_enable is None:
        self.shooter_enable = False
    else:
      self.id = 0
      self.level = 0
      self.remain_hp = 0
      self.max_hp = 0
      self.heat_cooling_rate = 0
      self.heat_cooling_limit = 0
      self.heat_speed_limit = 0
      self.gimbal_enable = False
      self.chassis_enable = False
      self.shooter_enable = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2B5H3B().pack(_x.id, _x.level, _x.remain_hp, _x.max_hp, _x.heat_cooling_rate, _x.heat_cooling_limit, _x.heat_speed_limit, _x.gimbal_enable, _x.chassis_enable, _x.shooter_enable))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 15
      (_x.id, _x.level, _x.remain_hp, _x.max_hp, _x.heat_cooling_rate, _x.heat_cooling_limit, _x.heat_speed_limit, _x.gimbal_enable, _x.chassis_enable, _x.shooter_enable,) = _get_struct_2B5H3B().unpack(str[start:end])
      self.gimbal_enable = bool(self.gimbal_enable)
      self.chassis_enable = bool(self.chassis_enable)
      self.shooter_enable = bool(self.shooter_enable)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2B5H3B().pack(_x.id, _x.level, _x.remain_hp, _x.max_hp, _x.heat_cooling_rate, _x.heat_cooling_limit, _x.heat_speed_limit, _x.gimbal_enable, _x.chassis_enable, _x.shooter_enable))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 15
      (_x.id, _x.level, _x.remain_hp, _x.max_hp, _x.heat_cooling_rate, _x.heat_cooling_limit, _x.heat_speed_limit, _x.gimbal_enable, _x.chassis_enable, _x.shooter_enable,) = _get_struct_2B5H3B().unpack(str[start:end])
      self.gimbal_enable = bool(self.gimbal_enable)
      self.chassis_enable = bool(self.chassis_enable)
      self.shooter_enable = bool(self.shooter_enable)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B5H3B = None
def _get_struct_2B5H3B():
    global _struct_2B5H3B
    if _struct_2B5H3B is None:
        _struct_2B5H3B = struct.Struct("<2B5H3B")
    return _struct_2B5H3B
